### ISSUE TITLE
Questions about different augmentors for sparse and dense gt.

### ISSUE THREAD

**Issue by zhujiagang** [princeton-vl/RAFT-Stereo#15]
Thanks for sharing your excellent work! Why do you provide two different ways for augmenting data? The sparse one does not have yjitter，asymmetric color augmentation. Besides, why do you provide a new function `resize_sparse_flow_map`, instead of using  `cv2.resize(flow, interpolation=cv2.INTER_NEAREST) `for resizing sparse gt?

**Comment by lahavlipson** [comment]
When altering sparse ground truth stereo, the mask of valid correspondences needs to be updated to reflect this change. This is what `resize_sparse_flow_map` does. 

Other than that, `SparseFlowAugmentor` and `FlowAugmentor` classes are pretty much the same, except the latter has a few extra features since the primary data we use for training (i.e. sceneflow) is dense.

**Comment by zhujiagang** [comment]
Is there any difference if we use `cv2.resize(flow, interpolation=cv2.INTER_NEAREST)` and` flow > 0` to set the valid flag, instead of `resize_sparse_flow_map`.

**Comment by lahavlipson** [comment]
Apologies, I didn't see your reply until now. When resizing the ground truth flow, you also need to scale the coordinates.

**Comment by zhujiagang** [comment]
Thanks a lot. Yes, we have resized the ground truth by `cv2.resize(flow, interpolation=cv2.INTER_NEAREST)` and scale.

**Comment by lahavlipson** [comment]
Closing this issue.
